# Generated by Django 3.2.22 on 2023-11-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_auto_20231114_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator',
            field=models.ImageField(default='avator.svg', null=True, upload_to=''),
        ),
    ]
