# Generated by Django 3.2.22 on 2023-11-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_user_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
