# Generated by Django 4.2.7 on 2023-11-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_alter_user_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.ImageField(default='profile/avatar.svg', null=True, upload_to='profile/'),
        ),
    ]
