# Generated by Django 4.2.7 on 2023-11-26 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0007_personalchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalchat',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
