# Generated by Django 4.2.7 on 2023-11-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0010_groupmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessages',
            name='receiver',
        ),
        migrations.AddField(
            model_name='groups',
            name='groupcode',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
