# Generated by Django 4.2.7 on 2023-11-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myvideos',
            name='type',
            field=models.CharField(choices=[('sale', 'sale'), ('free', 'free')], default='free', max_length=10),
        ),
    ]
