# Generated by Django 4.2.7 on 2023-11-24 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0004_remove_myvideos_views_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='myvideos',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='myvideos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 24, 12, 11, 23, 843879, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
