# Generated by Django 4.2.7 on 2023-11-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0005_myvideos_created_myvideos_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myvideos',
            name='video_image',
            field=models.ImageField(upload_to='videocover/'),
        ),
    ]
